src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    public function __construct()
    {
        $this->advertisement = new ArrayCollection();
    }

    public function __toString()
    {
        return $this->email;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }
}

templates/base.html.twig
<!DOCTYPE html>

<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>

        {% block stylesheets %}
            <link rel="shortcut icon" href="favicon.ico" type="image/x-icon">
            <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Spartan&display=swap">
            <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css" integrity="sha256-mmgLkCYLUQbXn0B1SRqzHar6dCnv9oZFPEC1g1cwlkk=" crossorigin="anonymous" />
            <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
            <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
            <link rel="stylesheet" href="{{ asset('build/css/app.css') }}">
            <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&display=swap">
                {{ encore_entry_link_tags('app') }}
        {% endblock %}

        {% block javascripts %}
            {{ encore_entry_script_tags('app') }}
        {% endblock %}
    </head>

    <body class="container-fluid" style="background-color: #F5EDDC;">
        <nav class="navbar " style="background-color: #E4DCCF;">
            <div class="container-fluid">
                <a href="{{ path('app_home_homepage') }}" class="navbar-brand fs-3">
                    <span class="fw-bold text-lg-start text-dark">
                        EASIER
                    </span>
                </a>
                {% if app.user %}
                    <div class="dropdown">
                        <button class="btn dropdown-toggle text-white" style="background: #19282F;" type="button" id="dropdownMenuButton2" data-bs-toggle="dropdown" aria-expanded="false">
                            {{ app.user.userIdentifier }}
                        </button>
                        <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="dropdownMenuButton2">
                            <li><a class="dropdown-item active" href="#">Action</a></li>
                            <li><a class="dropdown-item" href="#">Another action</a></li>
                            <li><a class="dropdown-item" href="#">Something else here</a></li>
                            <li><hr class="dropdown-divider"></li>
                            <li><a class="dropdown-item" href="{{ path('app_logout') }}">logout</a></li>
                        </ul>
                    </div>

                    <button class="btn btn-dark justify-content-around" style="position: absolute; top: 65px" type="button"  data-bs-toggle="offcanvas" data-bs-target="#offcanvasWithBothOptions" aria-controls="offcanvasWithBothOptions"><i class="fas fa-bars text-light"></i> </button>
                    <div class="offcanvas offcanvas-start w-25" data-bs-scroll="true" tabindex="-1" id="offcanvasWithBothOptions" aria-labelledby="offcanvasWithBothOptionsLabel">
                        <div class="offcanvas-header">
                            <h5 class="offcanvas-title" id="offcanvasWithBothOptionsLabel"><i class="fas fa-user"></i>{{ app.user.userIdentifier}} </h5>
                            <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
                        </div>
                        <div class="offcanvas-body list-group list-group-flush mx-3">
                            <a href="{{ path('app_home_homepage') }}" class="list-group-item list-group-item-action py-4 ripple" aria-current="true">
                                <i class="fas fa-tachometer-alt fa-fw me-3"></i><span>Нүүр хуудас</span>
                            </a>
                            <a href="#" class="list-group-item list-group-item-action py-4 ripple"
                            ><i class="fas fa-lock fa-fw me-3"></i><span>Хувийн мэдээлэл</span></a
                            >
                            <a href="{{ path('app_my_ads') }}" class="list-group-item list-group-item-action py-4 ripple"
                            ><i class="fas fa-globe fa-fw me-3"></i><span>Миний зарууд</span></a
                            >
                            <a href="#" class="list-group-item list-group-item-action py-4 ripple"
                            ><i class="fas fa-calendar fa-fw me-3"></i><span>Тусламж үйлчилгээ</span></a
                            >
                            <a href="#" class="list-group-item list-group-item-action py-4 ripple"
                            ><i class="fas fa-users fa-fw me-3"></i><span>Бидэнтэй холбогдох</span></a
                            >
                            <a href="{{ path('app_logout') }}" class="list-group-item list-group-item-action py-4 ripple"
                            ><i class="fas fa-money-bill fa-fw me-3"></i><span>Гарах</span></a
                            >
                        </div>
                    </div>

                    <div class="input-group border-top p-2 border-dark ms-5" >
                        <div class="form-outline input-group-sm">
                            <input type="search" placeholder="search" id="form1" class="form-control" />
                        </div>
                        <button type="button" class="btn btn-sm btn-dark">
                            <i class="fas fa-search"></i>
                        </button>
                    </div>

                    <div class="btn-group position-absolute" style="top: 70px; left: 350px">
                        <button type="button" class="btn btn-dark btn-sm dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                            Ангилал
                        </button>
                        <ul class="dropdown-menu dropdown-menu-dark">
                            <li><a class="dropdown-item" href="{{ path('app_advertisement_category', {id: 1}) }}">Pесторан, кафе, паб </a></li>
                            <li><a class="dropdown-item" href="{{ path('app_advertisement_category', {id: 2}) }}">Барилга, дэд бүтэц</a></li>
                            <li><a class="dropdown-item" href="{{ path('app_advertisement_category', {id: 3}) }}">Борлуулалт, худалдаа</a></li>
                            <li><a class="dropdown-item" href="{{ path('app_advertisement_category', {id: 4}) }}">Үйлдвэрлэл</a></li>
                            <li><a class="dropdown-item" href="{{ path('app_advertisement_category', {id: 5}) }}">Үйлчилгээ</a></li>
                            <li><a class="dropdown-item" href="{{ path('app_advertisement_category', {id: 6}) }}">Харуул хамгаалалт</a></li>
                            <li><a class="dropdown-item" href="{{ path('app_advertisement_category', {id: 7}) }}">ХТээвэр, гааль, агуулах</a></li>
                            <li><a class="dropdown-item" href="{{ path('app_advertisement_category', {id: 8}) }}">Банк, санхүү, нябо, нярав</a></li>
                            <li><hr class="dropdown-divider"></li>
                            <li><a class="dropdown-item" href="{{ path('app_advertisement_index') }}">Бүгдийг харах</a></li>
                        </ul>

                    </div>

                    <div class="position-absolute btn btn-sm btn-dark" style="top: 70px; left: 460px">
                        <a href="{{ path('app_advertisement_new') }}" class="text-decoration-none text-light">
                            Зар нэмэх <i class="fas fa-plus"></i>
                        </a>
                    </div>
                {% else %}
                    <a class="btn btn-sm btn-outline-secondary rounded-4" style="position: absolute; top: 15px; right: 30px;" href="{{ path('app_register') }}" role="button">Бүртгүүлэх</a>
                    <a class="btn btn-sm btn-outline-secondary rounded-4" style="position: absolute; top: 15px; right: 150px;" href="{{ path('app_login') }}" role="button">Нэвтрэх</a>
                {% endif %}
            </div>
        </nav>

        {% block body %}{% endblock %}

        <footer class="text-center bg-opacity-25 bg-secondary">
            Made with <i class="fa fa-heart text-danger"></i>
        </footer>
    </body>
</html>